#!/usr/bin/env python3
"""Measure whether the `Use when` phrasings actually select their own prompt.

Commit 878882a widened both descriptions and admitted the phrasings were
"drafted, not measured". This measures the part that can be measured, in two
passes:

  * every quoted example in every `description`, plus every phrase in
    hooks/vocabulary.json, run back through hooks/resolve.py inside carrier
    sentences — each must come back pointing at the prompt that claims it;
  * scripts/probes.json — sentences nobody copied out of a description, each
    with the prompt it should select, so a reworded description that breaks
    real routing fails here.

What this does NOT measure: whether the agent's own implicit matching fires on
the same words. That happens inside the model, where nothing here can see it.
A phrase passing here is unambiguous to the hook; it is not proof of
auto-invocation.

    ./scripts/check_phrasings.py             # report; non-zero on any failure
    ./scripts/check_phrasings.py --record    # rewrite docs/phrasings.md
    ./scripts/check_phrasings.py --check     # fail if that file is out of date
"""

import json
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "hooks"))

import resolve as resolver  # noqa: E402

DOC = REPO / "docs" / "phrasings.md"
PROBES = REPO / "scripts" / "probes.json"

# Stand-ins for the placeholders an example uses: "make X also do Y".
FILLERS = {"X": "the parser", "Y": "tabs", "Z": "the config file"}

# The same phrasing, as people actually type it.
CARRIERS = [
    "{p}",
    "can you {p}",
    "hey, {p}?",
    "before I push — {p}",
    "{p} when you get a chance",
]


def fill(text):
    return " ".join(FILLERS.get(w, w) for w in text.split())


def verdict_for(expected, trigger, matched, rivals, where):
    if trigger == expected:
        return "ok", ""
    if trigger is None and matched is not None:
        return "ambiguous", f"ties with {', '.join('/' + r for r in rivals)} on {where}"
    if trigger is None:
        return "missed", f"nothing matched on {where}"
    if expected is None:
        return "wrong", f"fired /{trigger} on {where}, expected silence"
    return "wrong", f"resolved to /{trigger} on {where}"


def check_phrases(phrases):
    """Each listed phrasing must select its own prompt, in every carrier."""
    results = []
    for phrase in phrases:
        verdict, detail = "ok", ""
        for carrier in CARRIERS:
            sentence = carrier.format(p=fill(phrase.text))
            trigger, matched, rivals = resolver.resolve(sentence, phrases)
            verdict, detail = verdict_for(
                phrase.trigger, trigger, matched, rivals, carrier.format(p="…"))
            if verdict != "ok":
                break
        results.append((phrase.trigger, phrase.text, phrase.source, verdict, detail))
    return results


def check_probes(phrases):
    """Sentences written from scratch must route where the file says."""
    data = json.loads(PROBES.read_text(encoding="utf-8"))
    results = []
    for probe in data["probes"]:
        prompt, expected = probe["prompt"], probe["expect"]
        trigger, matched, rivals = resolver.resolve(prompt, phrases)
        verdict, detail = verdict_for(expected, trigger, matched, rivals, "the sentence")
        results.append((expected, prompt, matched.text if matched else "", verdict, detail))
    return results


def render(phrase_results, probe_results):
    by_trigger = {}
    for trigger, text, source, verdict, detail in phrase_results:
        by_trigger.setdefault(trigger, []).append((text, source, verdict, detail))

    failed = sum(1 for r in phrase_results + probe_results if r[3] != "ok")
    lines = [
        "# Do the `Use when` phrasings select the right prompt?",
        "",
        f"**Generated by `scripts/check_phrasings.py --record` on {date.today():%d %B %Y}.**",
        "Regenerate it rather than editing it.",
        "",
        "**This measures the hook, not the agent.** `hooks/resolve.py` is the only",
        "matcher whose decision is visible from outside. Whether the agent's own",
        "implicit matching fires on these words happens inside the model, where nothing",
        "here can see it. A row marked ok is unambiguous to the hook; it is not proof",
        "that typing it invokes anything.",
        "",
        f"{len(phrase_results)} listed phrasings and {len(probe_results)} probe sentences, "
        f"{failed} failing.",
        "",
        "## Probes — sentences nobody copied out of a description",
        "",
        "The honest half of this page. Each is written from scratch in",
        "[`scripts/probes.json`](../scripts/probes.json) and says where it should land;",
        "`null` means the hook should stay silent.",
        "",
        "| Sentence | Expected | Matched on | Result |",
        "| --- | --- | --- | --- |",
    ]
    for expected, prompt, matched, verdict, detail in probe_results:
        want = f"`/{expected}`" if expected else "*silence*"
        on = f'"{matched}"' if matched else "—"
        mark = "ok ✅" if verdict == "ok" else f"{verdict} ⚠️ {detail}"
        lines.append(f"| {prompt} | {want} | {on} | {mark} |")

    lines += [
        "",
        "## Every listed phrasing, against itself",
        "",
        "Each quoted example in a `description`, and each phrase in",
        "[`hooks/vocabulary.json`](../hooks/vocabulary.json), inside five carrier",
        "sentences. This catches two prompts claiming the same words.",
        "",
        "| Prompt | Phrasing | Source | Result |",
        "| --- | --- | --- | --- |",
    ]
    for trigger in sorted(by_trigger):
        for text, source, verdict, detail in by_trigger[trigger]:
            mark = "ok ✅" if verdict == "ok" else f"{verdict} ⚠️ {detail}"
            lines.append(f'| `/{trigger}` | "{text}" | {source} | {mark} |')

    lines += [
        "",
        "## Reading a failure",
        "",
        "- **ambiguous** — two prompts claim the same words equally well. The hook stays",
        "  silent rather than guessing, so the phrasing buys nothing. Reword one side.",
        "- **wrong** — another prompt matched more specifically, or a sentence that",
        "  should have gone unanswered fired something.",
        "- **missed** — the example is too literal for a real sentence to match. Loosen",
        "  it, or add how you actually say it to `hooks/vocabulary.json`.",
        "",
        "## What is still not measured",
        "",
        "Auto-invocation itself. The agent matches the whole `description`, not the",
        "quoted fragments this page extracts, and it does so with judgement rather than",
        "a regex — it can fire on wording no example lists, and skip wording every",
        "example lists. Confirming that needs real use, one prompt at a time.",
        "",
    ]
    return "\n".join(lines)


GENERATED_LINE = "**Generated by"


def comparable(text):
    """The page minus its datestamp, so a rerun on a later day is not a diff."""
    return [l for l in text.splitlines() if not l.startswith(GENERATED_LINE)]


def main():
    phrases = resolver.load_phrases()
    phrase_results = check_phrases(phrases)
    probe_results = check_probes(phrases)

    args = sys.argv[1:]
    page = render(phrase_results, probe_results)

    if "--record" in args:
        DOC.write_text(page, encoding="utf-8")
        print(f"wrote {DOC.relative_to(REPO)}")
    elif "--check" in args:
        on_disk = DOC.read_text(encoding="utf-8") if DOC.is_file() else ""
        if comparable(on_disk) != comparable(page):
            print(f"{DOC.relative_to(REPO)} is out of date — "
                  "run ./scripts/check_phrasings.py --record")
            return 1

    failures = [r for r in phrase_results + probe_results if r[3] != "ok"]
    for first, second, _source, verdict, detail in failures:
        subject = f"/{first}" if first else "silence"
        print(f'{verdict:<9} {subject:<8} "{second}" — {detail}')

    total = len(phrase_results) + len(probe_results)
    if failures:
        print(f"\n{len(failures)} of {total} phrasings and probes do not resolve as recorded")
        return 1
    print(f"ok  {len(phrase_results)} phrasings and {len(probe_results)} probes resolve as recorded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
